package com.zyjz.bigdata.service;

import com.zyjz.bigdata.entity.BigDataConfig;

import java.util.List;

public interface BigDataConfigService {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data_config
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data_config
     *
     * @mbggenerated
     */
    int insert(BigDataConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data_config
     *
     * @mbggenerated
     */
    int insertSelective(BigDataConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data_config
     *
     * @mbggenerated
     */
    BigDataConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BigDataConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table big_data_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BigDataConfig record);

    List<BigDataConfig> selectAll();
}
